# Generated by Django 5.1.1 on 2024-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_task_recurrence_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
